# Tests on linux with gpu.

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

julia:1.5:
  extends:
    - .julia:1.5
    - .test
  tags:
    - nvidia

julia:nightly:
  extends:
    - .julia:nightly
    - .test
  tags:
    - nvidia
  allow_failure: true

coverage:
  extends:
    - .julia:1.5
    - .coverage
  allow_failure: true


# documentation:
#   extends:
#     - .julia:1.5
#     - .documentation
#   tags:
#     - nvidia

# pages:
#   stage: deploy
#   script:
#     - mv docs/build public
#   artifacts:
#     paths:
#     - public
#   only:
#     - master


# include:
#   - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/common.yml'
#   - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_v1.2.yml'
#   - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/coverage_v1.2.yml'
#   - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/documentation_v1.2.yml'
#   - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_v1.0.yml'
#   - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_v1.1.yml'
#   - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_v1.3.yml'
#   - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_dev.yml'

# test:dev:
#   allow_failure: true

# test:v1.3:
#   allow_failure: true

# coverage:
#   allow_failure: true

# test:v1.2:                      # cuda-memcheck version
#   script:
#     - julia -e 'using InteractiveUtils; versioninfo()'
#     - mkdir $JULIA_DEPOT_PATH # Pkg.jl#325
#     - julia -e 'using Pkg;
#                 Pkg.develop([PackageSpec(path=pwd());
#                              [PackageSpec(name=pkg)
#                               for pkg in split(get(ENV,"CI_DEV_PKGS",""))]])'
#     - julia -e "using Pkg;
#                 pkg\"test CUDAapi\";
#                 pkg\"test CUDAdrv\";
#                 pkg\"test CUDAnative\";
#                 pkg\"test CuArrays\";
#                 pkg\"build ${CI_PROJECT_NAME}\";
#                 pkg\"test --coverage ${CI_PROJECT_NAME}\""


# CUDA packages no longer compatible with julia < 1.3

# julia:1.0:
#   extends:
#     - .julia:1.0
#     - .test
#   tags:
#     - nvidia
#   allow_failure: true

# julia:1.1:
#   extends:
#     - .julia:1.1
#     - .test
#   tags:
#     - nvidia
#   allow_failure: true

# julia:1.2:
#   extends:
#     - .julia:1.2
#     - .test
#   tags:
#     - nvidia
#   allow_failure: true

# julia:1.3:
#   extends:
#     - .julia:1.3
#     - .test
#   tags:
#     - nvidia
#   allow_failure: true

# variables:
#   CI_IMAGE_TAG: 'cuda'
#   JULIA_NUM_THREADS: '4'
# image: juliagpu/cuda:10.1-cudnn7-cutensor-devel-ubuntu18.04

# variables:
#   JULIA_NUM_THREADS: '2'

#   - sm_75
# variables:
#   CI_THOROUGH: 'true'

